name: Python package

on:
  push:
    branches: master
  pull_request:
    branches: master

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.10", "3.11"]

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip setuptools
        python -m pip install testfixtures sympy mpmath jupyter matplotlib scipy nrpylatex
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - name: Install pdflatex and colordiff
      run: sudo apt-get install -y texlive-latex-base colordiff
    - name: Core Jupyter notebook testsuite
      run: |
        ./UnitTesting/core_Jupyter_notebook_testsuite.sh
